### ISSUE TITLE
Mouting Blob storage using Blobfuse ignores capacity?

### ISSUE THREAD

**Issue by dozer75** [kubernetes-sigs/blob-csi-driver#766] opened 2022-10-02 19:04 UTC
**What happened**:
I have been experimenting with BlobStorage and BlobFuse and I am setting storage capacity to 10Gi, but when I run df -h the mount size still states 15.6G. No matter which capcatiy I use it will always be mounted as 15.6Gi.

**What you expected to happen**:
The mount capacity should be the one requested.

**How to reproduce it**:

Follow the steps in https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-static

**Anything else we need to know?**:
I am currently learning how to use this, so of course it may be something here that I have misunderstood. 

But anyway my plans is to use a blob storage where the capacity may exceed 15.6 GB (it may be up to 1 TB) so I am a bit worried what implications this has.

**Environment**:

- CSI Driver version: v1.16.0
- Kubernetes version (use `kubectl version`): Azure Kubernetes Server 1.24.3, Client 1.25.2
- OS (e.g. from /etc/os-release): WSL Ubuntu 20.04.5 LTS (Focal Fossa)
- Kernel (e.g. `uname -a`): 5.10.102.1-microsoft-standard-WSL2
- Install tools:
- Others:

**Comment by andyzhangx** [comment] 2022-10-03 02:14
a blob storage container could store 100TB data, that's the limit, there is no size concept for blob storage container.

**Comment by dozer75** [comment] 2022-10-03 06:13
Yes it can, but why does the mount show 15.6GB as max then? You can't exceed that if you try to save files. I also tried using NFS and that shows petabytes on the mount so the capacity request is completely ignored in both circumstances.

I would like the capacity to be used as a restriction on how much a pod can store on a storage container. This is an effective way to restrict PVC creators to think about storage usages.

**Comment by andyzhangx** [comment] 2022-10-12 01:59
perf https://github.com/Azure/azure-storage-fuse/issues/543#issuecomment-744125667, this is by design, the total capacity is still 100TB as long as your cache on temp disk is not full, check below details:
```
 'df' on the mounted directory shows disk stats of the temp dir, this is by design. However this does not limit your storage container size by any means. File remains in temp directory only for a limited amount of time for local caching and then removed. Timeout is by default 120 seconds, and it can be configured by command line option "--file-cache-timeout-in-seconds".
```

I will close this issue, let me know if you have any other questions, thanks.

**Closed by andyzhangx** 2022-10-12 01:59 UTC
